name: Windows Build

on:
  workflow_dispatch: # 手动触发，PR 页面会显示按钮

jobs:
  build-windows:
    name: Build (Windows)
    runs-on: windows-latest
    env:
      BUILD_TYPE: Release
      UI_MODE: gui
      SCRIPTING_MODE: lua

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref }}
          submodules: 'recursive'

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - uses: aseprite/get-ninja@main

      - name: Prepare Skia (if GUI)
        if: env.UI_MODE == 'gui'
        shell: bash
        run: |
          if [[ -f "${GITHUB_WORKSPACE}/laf/misc/skia-url.sh" ]]; then
            this_dir=$(cygpath "${GITHUB_WORKSPACE}")
            skia_url=$(source "$this_dir/laf/misc/skia-url.sh" | xargs)
            skia_file=$(basename "$skia_url")
            curl --ssl-revoke-best-effort -L -o "$skia_file" "$skia_url"
            unzip "$skia_file" -d skia
          fi

      - name: Generate build files
        shell: bash
        run: |
          enable_ccache=off
          if [[ "$UI_MODE" == "gui" ]]; then laf_backend=skia; else laf_backend=none; fi
          if [[ "$SCRIPTING_MODE" == "lua" ]]; then enable_scripting=on; else enable_scripting=off; fi
          skia_arch=x64

          cmake -S . -B build -G "Ninja" \
            -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
            -DENABLE_SCRIPTING=$enable_scripting \
            -DENABLE_CCACHE=$enable_ccache \
            -DLAF_BACKEND=$laf_backend \
            -DENABLE_UPDATER=OFF \
            -DENABLE_NEWS=OFF \
            -DENABLE_WEBSOCKET=OFF \
            -DUSE_SHARED_CURL=OFF \
            -DCMAKE_USE_OPENSSL=OFF \
            -DCMAKE_USE_SCHANNEL=ON \
            -DSKIA_DIR=$(realpath skia) \
            -DSKIA_LIBRARY_DIR=$(realpath skia/out/Release-$skia_arch || true)

      - name: Compile
        shell: bash
        run: cd build && ninja -v

      - name: Copy Skia DLLs into build/bin (if any)
        if: env.UI_MODE == 'gui'
        shell: bash
        run: |
          skia_arch=x64
          if [[ -d "skia/out/Release-$skia_arch" && -d "build/bin" ]]; then
            find "skia/out/Release-$skia_arch" -maxdepth 1 -type f -iname '*.dll' -exec cp {} build/bin/ \;
          fi

      - name: Package build/bin into zip
        id: package_zip
        shell: pwsh
        run: |
          $ts = Get-Date -Format "yyyyMMdd-HHmmss"
          $zip = "aseprite-win-$ts.zip"
          Compress-Archive -Path "${{ github.workspace }}/build/bin/*" -DestinationPath $zip -Force
          "zip_path=$zip" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: aseprite
          path: ${{ github.workspace }}/build/bin

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-zip
          path: ${{ steps.package_zip.outputs.zip_path }}
